// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjk1KXIRU64jYd0lY76tqrkEUM1yepHA',
    appId: '1:623231973864:web:6dc8bb81444cfc9c56cc5d',
    messagingSenderId: '623231973864',
    projectId: 'fruits-ecommerce-926c7',
    authDomain: 'fruits-ecommerce-926c7.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-926c7.firebasestorage.app',
    measurementId: 'G-D72WL74RDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD45B1d93rcXsoSYkRHNqpbbGME3p1lfcc',
    appId: '1:623231973864:android:b214adaef32dacf556cc5d',
    messagingSenderId: '623231973864',
    projectId: 'fruits-ecommerce-926c7',
    storageBucket: 'fruits-ecommerce-926c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdREbrPWfgfqVtKTd6ar6uM4_yxuaK3Ig',
    appId: '1:623231973864:ios:31b68bd6ba160aec56cc5d',
    messagingSenderId: '623231973864',
    projectId: 'fruits-ecommerce-926c7',
    storageBucket: 'fruits-ecommerce-926c7.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdREbrPWfgfqVtKTd6ar6uM4_yxuaK3Ig',
    appId: '1:623231973864:ios:31b68bd6ba160aec56cc5d',
    messagingSenderId: '623231973864',
    projectId: 'fruits-ecommerce-926c7',
    storageBucket: 'fruits-ecommerce-926c7.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDjk1KXIRU64jYd0lY76tqrkEUM1yepHA',
    appId: '1:623231973864:web:79849d0d9cd098f956cc5d',
    messagingSenderId: '623231973864',
    projectId: 'fruits-ecommerce-926c7',
    authDomain: 'fruits-ecommerce-926c7.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-926c7.firebasestorage.app',
    measurementId: 'G-45PZ0PYMW4',
  );
}
